apiVersion: v1
kind: Namespace
metadata:
  name: skills
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: skills
  name: match
spec:
  selector:
    matchLabels:
      skills/app: match
  replicas: 1
  template:
    metadata:
      labels:
        skills/version: v1
        skills/app: match
    spec:
      nodeSelector:
         skills/dedicated: app
      containers:
      - image: 012345678900.dkr.ecr.ap-northeast-2.amazonaws.com/match-ecr:latest
        imagePullPolicy: Always
        name: app
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 200m
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: skills
  name: stress
spec:
  selector:
    matchLabels:
      skills/app: stress
  replicas: 1
  template:
    metadata:
      labels:
        skills/version: v1
        skills/app: stress
    spec:
      nodeSelector:
         skills/dedicated: app
      containers:
      - image: 012345678900.dkr.ecr.ap-northeast-2.amazonaws.com/stress-ecr:latest
        imagePullPolicy: Always
        name: app
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 200m
---
apiVersion: v1
kind: Service
metadata:
  namespace: skills
  name: match
spec:
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
  type: ClusterIP
  selector:
    skills/app: match
---
apiVersion: v1
kind: Service
metadata:
  namespace: skills
  name: stress
spec:
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
  type: ClusterIP
  selector:
    skills/app: stress
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  namespace: skills
  name: match
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: match
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 60
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  namespace: skills
  name: stress
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: stress
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 60